# Generated by Django 4.1.7 on 2023-03-28 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_usuario_rol"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.TextField(
                choices=[("empleado", "Empleado"), ("jefe", "Jefe")], default="Empleado"
            ),
        ),
    ]
