# Generated by Django 4.1.7 on 2023-03-30 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0004_cliente_producto_factura_detalle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="producto",
            name="stock",
            field=models.IntegerField(default=0),
        ),
    ]
