# Generated by Django 4.1.7 on 2023-03-30 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_producto_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="producto",
            name="foto",
            field=models.ImageField(default=None, upload_to=""),
        ),
    ]
