# Generated by Django 4.1.7 on 2023-04-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0009_alter_producto_foto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.TextField(default="cedula", max_length=10, unique=True),
        ),
    ]
