# Generated by Django 4.1.7 on 2023-04-03 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_alter_cliente_cedula"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="cedula",
            field=models.TextField(default="cedula", max_length=8, unique=True),
        ),
    ]
