# Generated by Django 4.1.7 on 2023-04-04 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_cliente_cedula"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalle",
            name="cantidad",
            field=models.FloatField(default=0),
        ),
    ]
