# Generated by Django 4.1.7 on 2023-04-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0012_detalle_cantidad"),
    ]

    operations = [
        migrations.RenameField(
            model_name="detalle",
            old_name="cantidad",
            new_name="Cantidad",
        ),
    ]
